[package]
name = "ch17-02-trait-objects"
version = "0.1.0"
authors = ["bmancini55 <bmancini@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
