[package]
name = "ch15-05-interior-mut"
version = "0.1.0"
authors = ["Brian Mancini <bmancini@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
